---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: "create /var/lib/docker, /mount/data/docker"
  file: path="{{ item }}" state=directory owner=root
  loop:
    - /var/lib/docker
    - /mount/data/docker

- name: "bind /var/lib/docker -> /mount/data/docker"
  mount:
    fstype: none
    opts: bind
    path: /var/lib/docker
    src: /mount/data/docker
    state: mounted

- name: Install Docker.
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  notify: restart docker

- name: Write daemon.json
  copy:
    content: "{{ docker_daemon_options | to_nice_json }}"
    dest: /etc/docker/daemon.json
  notify: restart docker

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers

- include_tasks: docker-compose.yml
  when: docker_install_compose

- include_tasks: docker-users.yml
  when: docker_users
